version: '3'

services:
  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.api
    environment:
      - DATABASE_READ_USER=postgres
      - DATABASE_READ_PASSWORD=postgres
      - DATABASE_WRITE_USER=postgres
      - DATABASE_WRITE_PASSWORD=postgres
      - DATABASE_DB=openaq
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - FETCH_BUCKET=openaq-fetches
      - ETL_BUCKET=openaq-fetches
      - FASTAPI_URL=http://localhost
      - DOMAIN_NAME=localhost
      - WAIT_HOSTS=db:5432
      - PGUSER=postgres
      - PGDATABASE=openaq
      - PGPASSWORD=postgres
      - PGHOST=db
      - OPENAQ_CACHE_TIMEOUT=30
    ports:
      - "8888:8888"
    volumes:
      - ..:/workspace
    depends_on:
      - db
    command: bash -c "cd /workspace/openaq_fastapi && pip install .[dev] && /wait && sleep 10 && openaqapi"

  db:
    build:
      context: ..
      dockerfile: openaq-db/docker/Dockerfile
    restart: unless-stopped
    volumes:
     - postgres-data:/var/lib/postgresql/data
     - ../openaq-db:/openaqdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=openaq
      - POSTGRES_PASSWORD=postgres
      - OPENAQ_APIUSER_PW=apiuserpw
      - OPENAQ_RWUSER_PW=rwuserpw
      - PGUSER=postgres
      - PGDATABASE=openaq
      - PGPASSWORD=postgres
      - PGHOST=db

volumes:
  postgres-data:
